name: custom deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    # ★ デプロイ用ジョブに environment を指定
    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリのコードをチェックアウト
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Node.js環境をセットアップ（バージョンはお好みで）
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) 依存パッケージをインストール
      - name: Install dependencies
        run: npm ci

      # 4) ビルドコマンド (package.json の "build": "vite build" を想定)
      - name: Build
        run: npm run build

      # 5) ビルド成果物(distフォルダ)をアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
        if: ${{ success() }}

      # 6) GitHub Pagesにデプロイ
      - name: Deploy
        uses: actions/deploy-pages@v1
        if: ${{ success() }}
